### PR TITLE
Fix missing unix socket usage in DatabaseConnectionInformation

### PR DESCRIPTION
**Pull request by nx-renezwinge**
### 1. Why is this change necessary?
We tried to install Shopware 6 on Google Cloud Run with Google Cloud SQL.
The default Google Cloud SQL Proxy runs over UNIX Socket.

But the installation doesn't add the socket to the DatabaseConnectionInformation.
So the Factory can't create the correct connection.

### 2. What does this change do, exactly?
Add unix socket input from installation form to DatabaseConnectionInformation.

### 3. Describe each step to reproduce the issue or behaviour.
Create a MySQL database with unix socket, not TCP. Start recovery installation and fill the optional unix socket input field. Clickt next. Then an error appears with SQLSTATE2002 Not path or file found

### 4. Please link to the relevant issues (if any).
x

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @reneznexum 
thanks for your contribution. unfortunately the travis build fails with your change

**Comment by nx-renezwinge** [comment]
Hi @mitelg 
i'm looking for the problem

**Comment by mitelg** [comment]
maybe you should only set the socket, if it's provided

**Comment by nx-renezwinge** [comment]
I checked this first. Some lines before is a check for the input paramters of the form and set the socket to an empty string.
And the Factory check the socket with empty().

**Comment by nx-renezwinge** [comment]
Hi @mitelg 
I searched for the problem, but i thought the failed tests is not a problem of my PR.
Just in a last step i checked out the current master branch and with this current state the unit tests also fails.

**Comment by mitelg** [comment]
oh ok, please do the PR against the `6.1` branch, as this is the current default

**Comment by nx-renezwinge** [comment]
New PR: https://github.com/shopware/platform/pull/405

**Comment by mitelg** [comment]
thanks for the hint with the failing travis build. it was an issue with the configuration, which was fixed here: https://github.com/shopware/platform/commit/ca14b22307e4d668ef37107d3c2e4587eafe8a87

**Comment by nx-renezwinge** [comment]
@mitelg Ah nice :) Thx for info.
I hope the new PR is ok.

**Pull request closed without merging**
