### PR TITLE
Add hint to set APP_ENV to dev for accessing the swagger documentation

### PR DESCRIPTION
**Pull request by Crease29**
### 1. Why is this change necessary?
I was trying to access the swagger documentation but just got an error all the time. To protect other users from this, I have adapted the documentation.

### 2. What does this change do, exactly?
It enhances the 030-admin-api-usage.md file.

### 3. Describe each step to reproduce the issue or behaviour.
:heavy_minus_sign: 

### 4. Please link to the relevant issues (if any).
:heavy_minus_sign: 

### 5. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by Crease29** [comment]
Hey, is there anything I can currently do to make the build succeed?

**Comment by mitelg** [comment]
hey @Crease29 
No, unfortunately the Travis build is currently broken

**Comment by Crease29** [comment]
Hey @mitelg, alright no probs. Please inform me, when I can rebase my branch 😊

**Comment by taltholtmann** [comment]
Hi @Crease29  
thank you for your contribution 🎉
Your PR was merged to 6.2 -> [Commit](https://github.com/shopware/platform/commit/f33e62bf479776200446535d7ba2f347816c79ac)

Best regards
Timo

**Pull request closed without merging**
