### PR TITLE
NEXT-8597 Translate scale units in admin

### PR DESCRIPTION
**Pull request by alexbaat**
### 1. Why is this change necessary?
To have the ability to translate scale units for proper translation in administration and storefront

### 2. What does this change do, exactly?
It adds a language switch to the Settings -> Shop -> Scale units page so scale units can be set per language

### 3. Describe each step to reproduce the issue or behaviour.
Go to the Settings -> Shop -> Scale units page and add scale units. Then switch language and translate them.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-8597

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Review by jleifeld — COMMENTED** [review]
I would add a entry in the changelog file for this addition :)

**Comment by alexbaat** [comment]
@jleifeld Thanks, just added it. Off course this file gives conflicts because everyone is editing it ;-)

**Comment by mitelg** [comment]
please add the ticket number to your commits. also squash your commits and add the `fixes #123` command

**Comment by GitEvil** [comment]
QA approved :heavy_check_mark:

**Review by jleifeld — APPROVED** [review]

**Comment by jleifeld** [comment]
You need to sign the cla before I can merge your PR :)

**Comment by alexbaat** [comment]
@jleifeld I already did that. Other pull request of yesterday is already merged.Or do I have to do it for every pull request?

**Comment by jleifeld** [comment]
It looks like a bug from the CLA plugin. We look for solution :)

**Comment by mitelg** [comment]
thanks for your contribution @alexbaat  :+1: :tada: :blue_heart:

**Pull request merged**
