### PR TITLE
Fix broken ./psh.phar storefront:watch command

### PR DESCRIPTION
**Pull request by audaki**
### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @audaki 

thank you very much for your contribution! :+1: 

But removing this command was intentionally as is had bugs and did not work like expected. We are going to remove the according PSH command, so there will be no confusing in the future. Sorry for that :slightly_smiling_face: 
see https://issues.shopware.com/issues/NEXT-13399

**Comment by audaki** [comment]
@mitelg Thank you for the clarification, if it's also removed from psh.phar it's fine!

IMPORTANT: What about ./psh.phar administration:watch? This command still exists and still works, is it also bug-ridden and should be replaced?

**Comment by mitelg** [comment]
no, the `administration:watch` works totally fine :slightly_smiling_face: 

beside the naming those two commands have technically not much in common :wink:

**Comment by audaki** [comment]
> no, the `administration:watch` works totally fine slightly_smiling_face
> 
> beside the naming those two commands have technically not much in common wink

Thank you for the answer and explanation :-)

**Pull request closed without merging**
