### PR TITLE
NEXT-7497 add handling for multiple primary keys in CachedEntityReader

### PR DESCRIPTION
**Pull request by FalkoHilbert**
add handling for multiple primary keys in CachedEntityReader.php

### 1. Why is this change necessary?

to handle muliple primary-keys in examlpe for many-to-many-relations in CachedEntityReader

### 2. What does this change do, exactly?

generate concatinated keys for primary-keys and use it as index for caching

### 3. Describe each step to reproduce the issue or behaviour.

create an entityDefinition with multiple primaryKeys and request them via Api

### 4. Please link to the relevant issues (if any).

https://issues.shopware.com/issues/NEXT-7497
#610 

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by ssltg** [comment]
Thank you for your contribution 👍 

can you please provide a Test for the changes? Just use the translation for a Test, as the Issue suggests.
You also need to sign the CLA so we can import this change.

Regards 🚀

**Comment by FalkoHilbert** [comment]
test is added,  but i could not accept the CLA, because there is no option to do it.
I've the same issue on bostday. @shyim is there any solution for that?

**Comment by shyim** [comment]
@FalkoHilbert Did you used the same a account where the commiter mail is also registered?

**Comment by FalkoHilbert** [comment]
> @FalkoHilbert Did you used the same a account where the commiter mail is also registered?

at least that's what I think. I actually only have one Github account and the commit is linked to the appropriate email address.

**Comment by shyim** [comment]
So the cla is now fixed for this PR.
The Installation of Shopware works now again (Github Action did reverted their change).
The Code-Style is still failing, can you check that? https://github.com/shopware/platform/runs/732368062?check_suite_focus=true#step:9:165

The failing PHPUnit test is not coming from this PR. A colleague is already looking into that.

**Comment by FalkoHilbert** [comment]
@shyim is there anything new, about the failing tests?

**Comment by shyim** [comment]
It's green on 6.2 branch. Rebase

**Pull request closed without merging**
