### PR TITLE
Implemented completion aware interface for stecman symfony console completion

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
### 1. Why is this change necessary?
For easier usability of console commands.

Did you ever recognized a whole uuid? Do you know by heart what the plugin was spelled?

Examples in usage were already shown in the [pull request for shopware 5](https://github.com/shopware/shopware/pull/1488).

### 2. What does this change do, exactly?
Implements for all core/shipped commands the CompletionAwareInterface
Adds hints in the documentation

### 3. Describe each step to reproduce the issue or behaviour.
Press tab to complete your shopware console commands. It just does not work.

### 4. Which documentation changes (if any) need to be made because of this PR?
☑  https://docs.shopware.com should get a hint on the setup and pros.
There is a complementary pull request to https://github.com/shopware/development/pull/20 to ensure this features is ready in the default docker container.

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
There is one point which needs autocompletion (in my point of view) and I am not sure how to implement it. So I'd like to have a review on the commited todo.

**Comment by mitelg** [comment]
regarding the docs: you know that they are here in the sources, too? :wink: so feel free to look for the right place by yourself here: https://github.com/shopware/platform/tree/master/src/Docs/_new :blush:

**Comment by JoshuaBehrens** [comment]
These are the same? :astonished: ok. nvm. Well I already did some changes to the docs so I guess this is already done.

**Comment by mitelg** [comment]
not the whole content but the part here: https://docs.shopware.com/en/shopware-platform-dev-en

**Comment by mitelg** [comment]
hey @JoshuaBehrens could you please rebase your branch? :blush:

**Comment by JoshuaBehrens** [comment]
Done.

**Comment by janbuecker** [comment]
Thank you @JoshuaBehrens. I've created an internal ticket to process your PR soon. You can track the status here: https://issues.shopware.com/issues/NEXT-3676

**Comment by janbuecker** [comment]
I've looked into your PR and it seems that you are missing a composer dependency which is required for your changes to work. In addition, the change in the `Dockerfile` will generate the completion just once for the current codebase. If you add a new command, you have to rebuild the whole container, don't you?

**Comment by JoshuaBehrens** [comment]
Oh :nose: it got lost after the rebase I suppose. The change in the docker container just adds a hint for the bash_completion package to ask the application with a specific command to get autocompletion for this application. So everytime you press tab bash_autocompletion asks the console for autocompletion. So it is completely dynamically. Otherwise I had to rebuild or restart anything by implementing these interfaces.

**Comment by mitelg** [comment]
hey @JoshuaBehrens 
thanks for your contribution. could you please sign the CLA?

**Comment by JoshuaBehrens** [comment]
CLA :astonished: ? here? Since?

**Comment by mitelg** [comment]
since the very beginning afaik :smile:

**Comment by JoshuaBehrens** [comment]
Is there a way that this is getting its way into Shopware 6.1?

**Comment by pantrtxp** [comment]
Hi @JoshuaBehrens,

as you might have noticed, this feature was not included in the 6.1 :( 

Given the age and the fact, that it was imported into a ticket I'm closing this issue.

Due to the issue you mentioned that our issuetracker does not inform about updates: we are currently looking into a fix for this. 

Sunny Regards
Pantrtxp

**Comment by JoshuaBehrens** [comment]
Ok now I am confused: do you want this feature or not? The target is master and therefore has not to be part of 6.1 just because I'd like to have it there. This pull request is marked as scheduled, the ticket is marked as important. Does having a ticket mean you want to implement it on your own as this code is now rejected? Do I have to keep my branch online so it can be merged later as this is marked scheduled?

When I perceive this correctly there is nothing missing here except time on your side to validate and merge this. Any rebase request might be delayed by myself but can be requested in the future.

**Comment by pantrtxp** [comment]
@JoshuaBehrens, sorry for this.

Please can create a new PR in regard of our new deprecation model since the master is our 6.2 development 

Sunny Regards
Pantrtxp

**Comment by JoshuaBehrens** [comment]
Is there some text online that explains the deprecation model? Is it part of the contribution guidelines?

I will keep that feature alive. This is part of my daily shopware 5 work and I miss it already in shopware 6.

**Comment by pantrtxp** [comment]
https://docs.shopware.com/en/shopware-platform-dev-en/api/api-versioning 
I have just looked into you're code in detail and do not see any deprecations or breaking changes as far as I can tell (not my field of work though)

**Comment by JoshuaBehrens** [comment]
Ok I will just retry it later

**Comment by JoshuaBehrens** [comment]
I request a rebased form of this branch in #573

**Pull request closed without merging**
