### PR TITLE
Fix doubled cart quantity #1008

### PR DESCRIPTION
**Pull request by djedrzejewski**
### 1. Why is this change necessary?
Because adding items to empty cart, when any promotion item is active, doubles the quantity of added items.

### 2. What does this change do, exactly?
It changes the way that errors in CartRuleLoader are handled - the error of type "PromotionCartAddedInformationError" is omitted, because it's logically not an error, so the cart is not saved "for persisting errors", which prevents preloading already filled cart, when it should be empty.

### 3. Describe each step to reproduce the issue or behaviour.
1. Create an promotion in Admin Panel -> Marketing -> Promotions, which is applicable in your current state
2. Try to add a item to the cart
3. Quantity should be doubled (you should see that two items was added in default)
Another way:
1. Make an successful order
2. Create an promotion in Admin Panel -> Marketing -> Promotions, which is applicable in your current state
3. Go to order history page and try to add to cart the order which you have made earlier
4. The added quantity should be doubled

Didn't tested with more than one item in cart, but it seems that the issue is independent of quantity for any product/item.

### 4. Please link to the relevant issues (if any).
https://github.com/shopware/platform/issues/1008

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by djedrzejewski** [comment]
I see that CLA don't work - but I agreed for it's statements

**Comment by J-Rahe** [comment]
Hi @djedrzejewski ,
I cannot reproduce this behaviour, could you check if you can still reproduce it?

**Comment by djedrzejewski** [comment]
@J-Rahe yup we checked it in shopware 6.2 and still is an issue. Can you describe the workflow? It's important to have empty cart and promotion, which is eligible to current state.

**Comment by J-Rahe** [comment]
@djedrzejewski 
I used a empty (psh init) dev shop, added a promotion (Marketing->Promotions) and added a 10% discount to the cart. Basically everything default. Can you give a detailed description on what your steps are using? Do you change anything in the promotion settings? (beside name, setting it to active and assigning sales channel and discount).

**Comment by J-Rahe** [comment]
Hey @djedrzejewski,
I still could not reproduce your issue, since there also has been no activity on this PR for quite some time now and it is outdated i will close your PR. If you can still reproduce the issue on the current master please open a new PR with a detailed Guide on how to reproduce the Issue.
Still thanks for making the effort!
best Regards,
 Johannes

**Pull request closed without merging**
