### PR TITLE
Fix path

### PR DESCRIPTION
**Pull request by boriskaiser**
### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @boriskaiser 
why do you think this needs to be changed? these are the right paths 
more information about your issue would be nice

**Comment by boriskaiser** [comment]
hey @mitelg,

> why do you think this needs to be changed?

Because it didn't work for me, see below.

**Test with the current path:**
`src/Resources/app/storefront/views/layout/header/logo.html.twig`

image


**Test with the new path:**
`src/Resources/views/storefront/layout/header/logo.html.twig`

image

---

I found the new path in the Academy Tutorial [Identifying overriding and extending blocks
](https://academy.shopware.com/courses/take/shopware-6-template-training-english/lessons/9181637-identifying-overriding-and-extending-blocks)

image

**Comment by tobiasberge** [comment]
Hi, @boriskaiser,

thanks for your contribution.

@mitelg I think Boris is right, those paths are not correct.

It should always be...

```
PluginName
    - Resources
        - <technical-domain> // e.g. views or app
             - storefront
             - administration
```
The Twig templates are inside the "views" folder, while the JavaScript application is under "app".

Best regards
Tobias

**Review by tobiasberge — APPROVED** [review]

**Comment by mitelg** [comment]
@boriskaiser @tobiasberge ups! sorry :see_no_evil: you are right. I confused it with the javascript stuff

**Comment by ssltg** [comment]
Hi @boriskaiser 
can you please sign the cla so we can import your changes?

thank you

**Comment by boriskaiser** [comment]
@ssltg 

> can you please sign the cla so we can import your changes?

Done:

image

**Comment by tobiasberge** [comment]
Hi @boriskaiser,

thanks again for helping out with the documentation. You Pull Request was merged to 6.2. 👍 Somehow the CLA check wasn't working properly and it showed me "pending" status.

Best regards
Tobias

**Pull request closed without merging**
