### PR TITLE
NEXT-4560 - If all configurator groups in the listing are expanded show the buy button - Fixes #805

### LINKED ISSUE #805: NEXT-4560 - Buy buttons for expanded variant products are not displayed in the category listing
EN:
Buy buttons for expanded variant products should be displayed in the storefront category listing instead of detail button.

DE:
Buy-Buttons für aufgefächerte Variantenprodukte sollten im Storefront Categorylisting angezeigt werden.

image

### PR DESCRIPTION
**Pull request by aragon999**
### 1. Why is this change necessary?
If all variant groups are configured such that they are expanded in the product listing, the products are essentially buyable. This PR is a first attempt to address this issue.

### 2. What does this change do, exactly?
If all product groups are expanded of a given variant product in the listing, the buy button is activated. If not all groups are expanded, the buy button is not shown.

### 3. Describe each step to reproduce the issue or behaviour.
Configure the variants like the screenshot
grafik
and look at the category (or use the search) where the product is assigned.

### 4. Please link to the relevant issues (if any).
#805 

### 5. Additional notes
As I developed this feature and also based on input of @OliverSkroblin I realized, that this is not an optimal solution, the following cases are not handled in a good customer friendly way:
1. The unique Variant groups and options are not displayed in the listing, therefore the variant name needs to be adjusted, to have a distinction between the variants.
2. If there are multiple variant groups and only some are expanded, and if additionally the listing in the storefront is filtered, the products can also be bought. Therefore if such a situation occurs, the buy button should also be enabled.
3. In addition to 2. if multiple filters are chosen in the listing, of the not expanded group, the result in the listing does not represent an unique variant. In that case the buy button should not be displayed. 

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by OliverSkroblin** [comment]
There will be changes that we have discussed. After the changes it can be merged.

**Comment by taltholtmann** [comment]
@aragon999 Could you please sign the license/cla, so that we can merge this PR.

**Comment by mitelg** [comment]
@taltholtmann I think he already has done that and there is this bug with this CLA plugin...

looking at his contribution history: https://github.com/shopware/shopware/pulls?q=is%3Apr+author%3Aaragon999+is%3Aclosed :wink:

**Comment by aragon999** [comment]
Hey, sorry I have not been home the last days. But as @mitelg said I think I have signed the CLA.
Is there something that I can do, to fix the problem with the CLA plugin?

**Comment by taltholtmann** [comment]
Hi @aragon999 
thank you for your contribution. 🎉
Your PR was merged to 6.2

Best regards
Timo

**Pull request closed without merging**
