### PR TITLE
NTR: Fix some spelling mistakes

### PR DESCRIPTION
**Pull request by SironheartAcc**
### 1. Why is this change necessary?
It fixes some minor spelling issues, which I have seen and fixed

### 2. What does this change do, exactly?
Fix spelling mistakes

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
I see no need to fix things in the `deprecated ` part of the docs. As they are, well, deprecated :wink:

**Comment by J-Rahe** [comment]
Hey @Sironheart,
could you please remove the deprecated parts as @mitelg suggested and remove the changelog.md? 
The changelog is not needed for fixing spelling mistakes.

**Comment by SironheartAcc** [comment]
> Hey @Sironheart,
> could you please remove the deprecated parts as @mitelg suggested and remove the changelog.md?
> The changelog is not needed for fixing spelling mistakes.

Have done so, also squashed the commits :)

**Comment by J-Rahe** [comment]
Hey @Sironheart, it seems i forgot to add an flag so the bot didn't auto close this PR on Merge. It is already merged, sorry for the delay and thanks for your contribution : )

**Comment by J-Rahe** [comment]
Here is the merge-commit https://github.com/shopware/platform/commit/5ac9f09958104ac12bf973e7c84f766123b81206

**Pull request closed without merging**
