### PR TITLE
Allow Cart LineItem Label Overwrite

### PR DESCRIPTION
**Pull request by Gugiman**
### 1. Why is this change necessary?
There is no possibility to overwrite the LineItem label.

### 2. What does this change do, exactly?
Add a Context Permission to allow overwrite the  label

### 3. Describe each step to reproduce the issue or behaviour.
Try to call setLabel ona LineItem Object.
The label will be overwritten every time.

### 4. Please link to the relevant issues (if any).
None found

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by Gugiman** [comment]
Someone knows what is wrong with those checks?

**Comment by shyim** [comment]
@Gugiman the code formatting does not pass. Maybe run ./psh.phar check:code I guess 🤔

**Comment by Gugiman** [comment]
psh doesn't know that command

**Comment by pweyck** [comment]
Thanks for your contribution @Gugiman

**Pull request closed without merging**
