### PR TITLE
Add how to for administration search

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
### 1. Why is this change necessary?
Describe in steps how to add your own entity search

### 2. What does this change do, exactly?
Adds my notes on adding my own entity to the global search

### 3. Describe each step to reproduce the issue or behaviour.
1. How do I get myself into the search
2. There is no explanation
3. Let's find it out
4. Document it for later
5. PR

### 4. Which documentation changes (if any) need to be made because of this PR?
This is a documentation change

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by almare** [comment]
Thank you for the documentation, but I have a problem with the visibility of the found items. I receveive the correct items with a name column, but the result set is just showing empty lines. Do you have any suggstions why this is happening?

**Comment by JoshuaBehrens** [comment]
Sounds like there is a failure changing the `sw-search-bar-item` template. Can you zip/git up your plugin? I can find it if you like.

**Comment by almare** [comment]
[BundleExample.tar.gz](https://github.com/shopware/platform/files/3701518/BundleExample.tar.gz)
Hope this helps

**Comment by JoshuaBehrens** [comment]
If I see it correctly you are missing to include your `core/structure/sw-search-bar-item/index.js` in the `main.js`. For now the template is not extended

**Comment by mitelg** [comment]
thanks for your contribution @JoshuaBehrens :+1: :tada: :blue_heart:

**Pull request closed without merging**
