### PR TITLE
Documentation: Change POST to GET, as POST is not allowed

### PR DESCRIPTION
**Pull request by jakobsturm**
As far as I have noticed, the POST method is not allow on this url. Only GET will work.

### CODE REVIEW

**Comment by mitelg** [comment]
according to this annotation https://github.com/shopware/platform/blob/master/src/Core/Checkout/Customer/SalesChannel/CustomerRoute.php#L71 both will work

**Comment by jakobsturm** [comment]
Unfortunately not, with POST I receive this error:

`{
    "errors": [
        {
            "code": "0",
            "status": "405",
            "title": "Method Not Allowed",
            "detail": "No route found for \"POST /store-api/v3/account/customer\": Method Not Allowed (Allow: GET)",
            "meta": {
                "trace": [
                    {
                        "file": "/app/vendor/symfony/event-dispatcher/Debug/WrappedListener.php",
                        "line": 126,
                        "function": "onKernelRequest",
                        "class": "Symfony\\Component\\HttpKernel\\EventListener\\RouterListener",
                        "type": "->",
                        "args": [
                            {},
                            "kernel.request",
                            {}
                        ]
                    },`
...

**Comment by shyim** [comment]
Maybe just old version?

**Comment by jakobsturm** [comment]
Yes, this was the problem. We are still on 6.2.9 where only GET is allowed. Thanks for the clarification!

**Pull request closed without merging**
