### PR TITLE
[Bugfix] Excluding non shipping available countries

### PR DESCRIPTION
**Pull request by bystro**
### 1. Why is this change necessary?
That is a bugfix.

### 2. What does this change do, exactly?
1. We are able to exclude country from a delivery address.
The bugfix excludes a non `Shipping available` countries from delivery address forms.
2. Excludes non `Shipping available` countries from `Shipping country` list in cart view.

### 3. Describe each step to reproduce the issue or behaviour.
3.1. Delivery address forms
3.1.1. Go to admin panel
3.1.2. Activate one of the country but uncheck `Shipping available` option.
3.1.3. Assign this country to a sales channel you are using.
3.1.4. Open registration form at storefront. You will probably see the additional country in a shipping address section besides you made this country **shipping unavailable**.

obraz

3.2. Shipping country list in cart view
3.2.1. Add a product to the cart
3.2.2. Click inside the cart-sidebar "Go to cart"
3.2.3. Click "Shipping cost"  and a country-drop-down menu appears You will probably see countries that are **shipping unavailable** also.

image

### 5. Checklist
- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by pweyck** [comment]
> **Krzysztof Kubacki** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=1087) it.

Hi @bystro,

could you check that? It seems like you singed with an email address that's not connected to your github account.

**Comment by bystro** [comment]
@pweyck 
I have signed the CLA but seems the same issue like before
obraz

**Comment by bystro** [comment]
I have updated this PR by `Excludes non Shipping available countries from Shipping country list in cart view.` case.

**Comment by J-Rahe** [comment]
Hey @bystro,
please rebase.

**Comment by bystro** [comment]
ok I rebased to master :)

**Comment by J-Rahe** [comment]
Hey @bystro your PR seems good so far but is missing an changelog and some tests, could you add these?

**Comment by philipreinken** [comment]
Hello, we're closing this pull request due to inactivity. If this change is still important to you, feel free to create a new pull request.

For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline.

**Pull request closed without merging**
