### PR TITLE
BUG: http cache and missing canonical link

### PR DESCRIPTION
**Pull request by hlohaus**
### 1. Why is this change necessary?

fixed a bug. see 3.

### 3. Describe each step to reproduce the issue or behaviour.

1. Enable http cache.
2. open a seo page.
3. open the seo page with a alternativ url
4. see that canonical link are not set

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by OliverSkroblin** [comment]
Hey @hlohaus,

Thank you for pointing that out. The http cache should not place the same page under different caches. The current problem is, if I understood it correctly, that the Canonical is not set correctly if the page was called with different urls. This should be corrected by the Seo implementation.  The replacement should take place after the http cache.

**Comment by OliverSkroblin** [comment]
I just spoke with a colleague. We are currently setting a meta tag and a header, I think. Which link is currently not set correctly?

**Comment by hlohaus** [comment]
Yes, it would be set in onRequest and that are not called if the http cache is active

**Comment by OliverSkroblin** [comment]
Ahh okay, that is easy. I will take care of it. Thanks again.

**Comment by hlohaus** [comment]
Incidentally, I noticed it in connection with this plugin:
https://store.shopware.com/she5388885409742/weiterleitung-zur-canonical-url.html

**Comment by OliverSkroblin** [comment]
@hlohaus we fixed it with this commit: https://github.com/shopware/platform/commit/82586e206d8429c975ad36dda5d248c0eeec4f9d

**Pull request closed without merging**
