### PR TITLE
Require vendor/autoload.php of plugins if it exists

### PR DESCRIPTION
**Pull request by windaishi**
### 1. Why is this change necessary?
If a plugin is not installed via composer but still comes with own dependencies, currently the plugin has to take cake to require this dependencies itself. In particular this means it has to 
 require its own`vendor/autoload.php`. 

This has two disadvantages:

* This code is duplicated in every plugin.
* The plugin itself has to decide whether it has to load its `vendor/autoload.php`. In case the plugin is managed by composer, there is no need for the plugin to require its `vendor/autoload.php`. The plugin can currently not decide this because it has no access to the `managed_by_composer` flag.

### 2. What does this change do, exactly?
This PR changes the method `\Shopware\Core\Kernel::registerPluginNamespaces` to automatically load the file `vendor/autoload.php` of each plugin if present instead of registering only the namespaces listed in the plugin's `composer.json`.
Registering the namespaces this way has the advantage that also the namespaces of all shipped dependencies are registered.

In case there is no `vendor/autoload.php` bundles with the plugin, the namespaces from the plugin's `composer.json` are still loaded.

### 3. Describe each step to reproduce the issue or behaviour.
N/A

### 4. Please link to the relevant issues (if any).
N/A

### 5. Which documentation changes (if any) need to be made because of this PR?

N/A

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
This should be also deactivateable. In Shopware 5 we had sometimes library conflict issues and required the autoload only in this specific case.

**Comment by windaishi** [comment]
Could you tell me an example case where this should be possible? If you have library conflicts you still have the possibility to install the plugin via composer or, as a plugin vendor, just to not ship the `vendor/autoload.php`.

**Comment by shyim** [comment]
Core ships Guzzle 5, Plugin have to use a payment library which requires Guzzle 6.
Global require of plugin breaks components which uses guzzle 5. So a fix was to load the custom autoload.php when the own controller was called.

**Comment by shyim** [comment]
And your case is not valid. A plugin don't need to know is it managed_by_composer. 
Little example :wink: 
https://github.com/FriendsOfShopware/FroshProfiler/blob/master/FroshProfiler.php#L18-L20

**Comment by mitelg** [comment]
@shyim what about downloading the packed plugin from the store (plugin brings vendor directory) but then the shop manager installs it via composer. now the plugin dependencies are in the root vendor directory and also in the plugin. just checking if the autoload file in the plugin is there, is not enough

**Comment by shyim** [comment]
When you install it using composer, the dependencies are in the vendor folder of the project and **not in plugin**

**Comment by mitelg** [comment]
but if you ship the plugin with the vendor directory in the plugin, because you have uploaded it to the store. did you even read my message? :smile:

**Comment by shyim** [comment]
Never mind. Solved all questions

**Comment by windaishi** [comment]
I close this PR as the suggested option to automatically load the `autoload.php` leads to more complex problems I did not suspect when opening this PR.

One of the problems is the following: When multiple plugins bring in the same dependency then it is not assured that the newest dependency is loaded. Therefore I think it is better for every plugin to do its dependency management itself.

**Pull request closed without merging**
