### PR TITLE
Fixes #1261 Adds maxlength validation for category seo description

### LINKED ISSUE #1261: "Please fill in all required fields" on too long meta description
**Description**  
When the meta description of a category is too long (over 255 chars) the backend will say "Please fill in all required fields" instead of actually pointing out the problem.

**Possible Solution**  
Add client-side validation for field length on meta description field.

**Additional context**  
Screenshot 2020-08-22 at 08 57 59
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by runelaenen**
### 1. Why is this change necessary?
When the meta description of a category is too long (over 255 chars) the backend will say "Please fill in all required fields" instead of actually pointing out the problem.

### 2. What does this change do, exactly?
* Added `sw-field-helpers` slot to `sw-base-field` and `sw-block-field`
* Added property `maxLength` to `sw-textarea-field` component to add maximum length validation
* Added `maxLength` to Category SEO Description field to reflect max length in database
* Sets 255 as maxLength for SEO Description for Categories

### 4. Please link to the relevant issues (if any).
https://github.com/shopware/platform/issues/1261

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by tinect** [comment]
If I fill the metaDescription in categories for more than 255 characters there is no error. The text is truncated automatically. 🤔

**Comment by runelaenen** [comment]
> If I fill the metaDescription in categories for more than 255 characters there is no error. The text is truncated automatically. 🤔

Hmm weird. On what version? I can just keep on typing and it will give the error from the screenshot in #1261 when I try to save.

**Comment by tinect** [comment]
> Hmm weird. On what version? I can just keep on typing and it will give the error from the screenshot in #1261 when I try to save.

I'm on 6.3.0.2, now tested on master with same behaviour.
But, for sure, I like the PR :-)

**Comment by tinect** [comment]
Ahhhh, I can reproduce this issue in products. Maybe you could extend your PR to sw-text-fields, too ?

**Comment by runelaenen** [comment]
> Ahhhh, I can reproduce this issue in products. Maybe you could extend your PR to sw-text-fields, too ?

Yes I'll take a look at it later this week :+1:

**Comment by runelaenen** [comment]
> Ahhhh, I can reproduce this issue in products. Maybe you could extend your PR to sw-text-fields, too ?

Done! I also moved the logic (which would have been double in text-field and text-area) to a seperate component.

**Comment by pweyck** [comment]
Hi @runelaenen, your changes look nice. Could you write a test? You can find the docs [here](https://docs.shopware.com/en/shopware-platform-dev-en/references-internals/testing/jest)

**Comment by runelaenen** [comment]
> Hi @runelaenen, your changes look nice. Could you write a test? You can find the docs [here](https://docs.shopware.com/en/shopware-platform-dev-en/references-internals/testing/jest)

Hi @pweyck 
Sorry for the delay, I'm switching jobs so had to set up my dev environment again on a new laptop 🤡 
I've added the tests! It's my first time writing jest tests, is it OK like this?

**Comment by runelaenen** [comment]
Hi @pweyck 
Can I get another update on this? It's been almost a month. Is there anything else I can/have to change before this can be merged?

**Comment by philipreinken** [comment]
Hi @runelaenen , thank you for your time. Unfortunately we can't merge this change, because the base components have been altered here and therefore affect the whole administration. This is quite risky and very hard to test. We think this issue is important though, so please consider implementing the fix in a less generic way for the problematic module only (for example by just changing the error message to a more helpful one).

**Pull request closed without merging**
