### PR TITLE
NEXT-4852 - fixed baseUrl for hot-reload mode

### PR DESCRIPTION
**Pull request by ChristopherDosin**
`://` is wrong and the files won't be loaded - It has to be `//`.

### 1. Why is this change necessary?
The JS files in hot-reload mode won't be loaded because `://` is a wrong path. It has to be `//`.

### 2. What does this change do, exactly?
Fixed the path to the js files for hot reloading

### 3. Describe each step to reproduce the issue or behaviour.
If you're using the hot-reload for the storefront `./psh.phar storefront:hot` JS files are loaded like `://url:9999/js/app.js`. Because of the the wrong path ( `://` ) the JS files can't be loaded. The path hast to be `//`.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-4852

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by jenskueper** [comment]
Hey there,

thank you for the PR. Is the REQUEST_SCHEME empty/null in your case? The code should work fine as long as there is a valid REQUEST_SCHEME like http or https. If we remove the **:** it breaks on all setups with a valid REQUEST_SCHEME. Can you provide some information about your setup?

Best regards
Jens

**Comment by ChristopherDosin** [comment]
> Is the REQUEST_SCHEME empty/null in your case? 

Yes, `REQUEST_SCHEME` returns `null` in my case. My url is `http://development.test/`. I am using valet-plus for my local dev environment and the latest `shopware/development` git version.

And without my fix, the js url's are `://development.test:9999/js/app.js"` which is of course not working because of the `:`.

If i secure my url with a SSL cert e.g `https://development.test` `REQUEST_SCHEME` is still returning `null` and i have the same bug - The urls are still `://development.test:9999/js/app.js"`

**Comment by ChristopherDosin** [comment]
@jenskueper I installed the `shopware/development` now also on my dev server which is handled by laravel forge - SSL enabled. Same issue. Files are loaded with `://development.test:9999/js/app.js"` in the hot-reload mode.

**Comment by Alex--C** [comment]
I'm guessing the problem is the Apache/Nginx version. According to https://stackoverflow.com/a/23177714, `$_SERVER['REQUEST_SCHEME']` was introduced in Apache 2.4. My macOS MAMP stack uses Apache 2.2 and `REQUEST_SCHEME` is not available.

`REQUEST_SCHEME` is not mentioned on https://www.php.net/manual/en/reserved.variables.server.php, probably it would be safer to use $_SERVER['HTTPS'].

As far as I know `app.request.getScheme()` is based on `$_SERVER['HTTPS']` and does exactly what we'd need here.

So my suggestion would be:
`{% set baseUrl = app.request.getScheme() ~ '://' ~  app.request.server.get('SERVER_NAME') %}`

CC @ChristopherDosin , maybe you can update your pull request.

**Comment by ChristopherDosin** [comment]
@Alex--C Yes, seems to work - However i am not using Apache, i am on macOS with nginx / valet. @jenskueper  I updated the PR.

**Review by mitelg — COMMENTED** [review]
maybe we could also use app.request.getHost here? instead of getting SERVER_NAME directly

**Comment by Alex--C** [comment]
> maybe we could also use app.request.getHost here? instead of getting SERVER_NAME directly

IIRC getHost contains the port (:8888 for example). That would mess up hot reloading as we would get URLs like `http://localhost:8888:9999/js/app.js`.

EDIT: I might have confused `getHost` with `getHttpHost`, `getHost` might work!

EDIT2 (sorry...): Yes, `getHost` works in my case: `app.request.getScheme() ~ '://' ~ app.request.getHost()` => `http://localhost` when running on `http://localhost:8888`, so all good with `getHost`.

**Comment by ChristopherDosin** [comment]
works in my case too with `http` & `https` and with a dev url like `development.test`. I adjusted the PR again.

**Comment by mitelg** [comment]
@ChristopherDosin could you also rebase your branch to current master? there is a conflict

**Comment by ChristopherDosin** [comment]
@mitelg Sure, sorry about that - done.

**Comment by mitelg** [comment]
thanks for your contribution @ChristopherDosin :+1: :tada: :blue_heart:

**Pull request closed without merging**
