### PR TITLE
Add missing product gateway criteria event

### PR DESCRIPTION
**Pull request by jochenmanz**
### 1. Why is this change necessary?
Currently no event is present for changes to the criteria used inside the product cart processor.

### 2. What does this change do, exactly?
Just adds the required event

### 3. Describe each step to reproduce the issue or behaviour.
Imaging decorating the ProductCartProcessor and needing new product related data.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Review by philipreinken — CHANGES_REQUESTED** [review]
Hi @jochenmanz , thank you for creating this pull request :slightly_smiling_face: Please add tests for your changes.

**Comment by jochenmanz** [comment]
@philipgatzka i've added a test for the new event.

**Comment by jochenmanz** [comment]
Is there still something to do? @philipgatzka

**Review by philipreinken — APPROVED** [review]
Not as far as I'm concerned, thanks for the update :+1:

**Comment by philipreinken** [comment]
Thank you for contributing @jochenmanz ! :rocket:

**Comment by almare** [comment]
When will this be released? It looks like it's ready since November last year.

**Comment by mitelg** [comment]
hello @almare 
is this was a bit to late for the last release in December (6.3.4.0), it will be part of the upcoming 6.3.5.0 release in the beginning of February

**Pull request closed without merging**
