### PR TITLE
Set shipping method id on guest checkout solves #1366

### PR DESCRIPTION
**Pull request by mmeester**
### 1. Why is this change necessary?
See issue #1366 

### 2. What does this change do, exactly?
See issue #1366 

### 3. Describe each step to reproduce the issue or behaviour.
See issue #1366 

### 4. Please link to the relevant issues (if any).
Solves issue #1366 

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
Can you provide a Test. Does this affect also the Store-API?

**Comment by mmeester** [comment]
@shyim I'm finding it kind of hard to determine what needs to be done, this is fix for a problem, I assume the function itself already has a test written?

**Comment by shyim** [comment]
There are already tests for this controller.
https://github.com/shopware/platform/blob/042645ff73df274936dcbaa3053975afb3e36895/src/Core/Checkout/Test/Cart/SalesChannel/SalesChannelCheckoutControllerTest.php#L23

But It would be cool, when you can add an additional test case for this specific case.
Maybe we can use `\Shopware\Core\System\SalesChannel\Context\SalesChannelContextServiceInterface::get` to get the SalesChannelContext. So it would consider all parameters and not only this one :)

**Comment by pweyck** [comment]
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

**Pull request closed without merging**
