### PR TITLE
Prevent unfiltered media search

### PR DESCRIPTION
**Pull request by AlexBachmann**
The setMediaItem method is vulnerable to trigger an unfiltered media search, resulting in an application failure, because of a timeout (thousands of results could not be retrieved in time) or a blocking issue (the huge json response needs to be parsed, which is a blocking operation).

Unfortunately this vulnerability is already causing problems:

```js
this.paymentMethodRepository.get(this.paymentMethodId)
                .then((paymentMethod) => {
                    this.paymentMethod = paymentMethod;
                    this.setMediaItem({ targetId: this.paymentMethod.mediaId });
                })
                .finally(() => {
                    this.isLoading = false;
});
```
Here, if a payment method does not have a mediaId assigned to it, it causes all media items to be loaded.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by NiklasLimberg** [comment]
Hi @AlexBachmann,
you still need to provide a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md), otherwise it  looks good so far. Btw please include the issue-key in the changelog

**Comment by NiklasLimberg** [comment]
Hi @AlexBachmann,
I just saw, you still need to sign the CLA

**Comment by NiklasLimberg** [comment]
Hi @AlexBachmann,
are you still working on this?
If you arn't I'll close this PR in 2 days

**Comment by shyim** [comment]
Hey,

I am closing this PR as it's inactive. If you still want to work on it. Please create a new Pull request. :smile:

**Comment by lacknere** [comment]
I've created a PR for this issue at #2957 
@NiklasLimberg @shyim

**Pull request closed without merging**
