### PR TITLE
* fix using arrow functions untranspiled

### PR DESCRIPTION
**Pull request by MDSLKTR**
### 1. Why is this change necessary?
IE 11 does not support arrow functions, so this tracking event will not be fired in IE 11. This code is not transpiled and therefore not es5 compatible.

### 2. What does this change do, exactly?
Use a plain old function in the template to be es5 compatible.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
What is the problem when this remains like it is now?

**Comment by MDSLKTR** [comment]
> What is the problem when this remains like it is now?

IE 11 support https://caniuse.com/#feat=arrow-functions

**Review by px-flo — APPROVED** [review]

**Comment by JoshuaBehrens** [comment]
Ah ok. I just see the name of your branch. Maybe a short sentence in the description next time for those who are not seeing the obvious 🙈

**Comment by MDSLKTR** [comment]
> Ah ok. I just see the name of your branch. Maybe a short sentence in the description next time for those who are not seeing the obvious 🙈

Sorry i missed the description 👍 It should be better explained now

**Comment by raknison** [comment]
Hey @MDSLKTR ,

thank you for your contribution 🎉
Your PR was merged to master.

Best regards
Markus

**Pull request closed without merging**
