### PR TITLE
Twig block around CMS Create Wizard options

### PR DESCRIPTION
**Pull request by runelaenen**
### 1. Why is this change necessary?
To properly create a new cms page type.

### 2. What does this change do, exactly?
Add a twig block around existing code.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by runelaenen** [comment]
@shopwareBot  Why did this get closed? Can this not be added to the project?

**Comment by Haberkamp** [comment]
@runelaenen i think the bot hat closed this Pull Request because it got merged into the 6.1 branch.

Anyways, thank you for your contribution.

**Comment by mitelg** [comment]
@runelaenen the PR got closed because we add a little note to the commit message `Fixes #501` see: https://github.com/shopware/platform/commit/75c8c2ee1d5f0807d643781775414603f6921148 (or click on the link in the closed message :wink: )
We do that, as we import the PRs into our internal Git repository, rebase them, maybe adjust them and afterwards the code gets synced back to Github.

**Comment by runelaenen** [comment]
Okay thank you, that's clear!

**Pull request closed without merging**
