### PR TITLE
Move seo url related migrations from storefront to core

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
### 1. Why is this change necessary?
Due to the migrations being in the storefront package that is not reffered to by the core packages the entities in the core don't have the tables they need present when you only install the core package.

### 2. What does this change do, exactly?
It deletes old migrations that could've been running that are related to this and adds similar migrations that have the same effect

### 3. Describe each step to reproduce the issue or behaviour.
1. `composer require shopware/core`
2. Run migrations
3. Run indexers. The seo update will fail as the entity exists but not the table

### 4. Quick fix
`composer require shopware/storefront` :trollface: 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
As @OliverSkroblin suggest I deleted former migrations as changing existing ones is a no-go.
As @pweyck suggest I took the current schema to recreate the table in core later on.

**Comment by jkrzefski** [comment]
@pweyck I want to point out how this change could potentially break blue/green. As @JoshuaBehrens pointed out, migrations are deleted and new migrations are added with the accumulated schema changed of the old migrations. The new migrations only run if their respective tables do not exist yet. But this can lead to problems if a table already exists, but not every alteration from the deleted migrations has been applied yet.

Say we have a system where [Migration1536232990SeoUrl](https://github.com/shopware/platform/blob/bc3041e310f0e347220b527819145f1e4e13de48/src/Storefront/Migration/Migration1536232990SeoUrl.php) already ran, but [Migration1568787535AddSeoUrlConstraints](https://github.com/shopware/platform/blob/bc3041e310f0e347220b527819145f1e4e13de48/src/Storefront/Migration/Migration1568787535AddSeoUrlConstraints.php) did not. Now both of them are gone and the new migration will not run, because the table already exists. So now the schema is not up to date anymore, but all the migrations ran "correctly".

I suggest to create new migrations as exact copies of the deleted ones, so that every deleted migration gets exactly one replacement. The replacement migrations would then check the migration table for the migration they are replacing and will only run if the replaced migration has not yet run.

**Comment by pweyck** [comment]
These migrations are pretty old and are all contained in v6.1.0. So in this case, it should not be a problem.

But I agree, that we need to be really careful when squashing migrations.

**Comment by pweyck** [comment]
Thanks @JoshuaBehrens for this PR! I also fixed other dependencies on the storefront bundle. (But I did not test it completely)

**Comment by JoshuaBehrens** [comment]
Woop woop 🎉 Thanks for your further investigations

**Pull request closed without merging**
