### PR TITLE
Buy widget template: create new blocks and templates

### PR DESCRIPTION
**Pull request by danielwolf1**
### 1. Why is this change necessary?
The current structure makes it hard to change the rules if the main price should be displayed for block prices as well. 

### 2. What does this change do, exactly?
It extracts the template code of normal prices and block prices into new template files.

### 3. Describe each step to reproduce the issue or behaviour.
- 

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by OliverSkroblin** [comment]
Hey,

thanks for your contribution. However, your changes break current overrides of this template. Unfortunately, Twig does not allow you to overwrite blocks of an included template. I think, for compatibility you would have to work with the embed function of Twig:

https://twig.symfony.com/doc/3.x/tags/embed.html

**Comment by pantrtxp** [comment]
Hi @danielwolf1, you still need to accept the "Contributor License Agreement" before we can go on with this PR

**Comment by danielwolf1** [comment]
@pantrtxp I did accept it, now

@OliverSkroblin I know but in my opinion, this is very important now - in a few month, this change will break much more. It's a huge template file which can't be extended properly without this change.

**Comment by pweyck** [comment]
Hello @danielwolf1, we simply cannot merge breaking changes (besides security issues). I understand why you want to change this. If you find a way to make this non-breaking, we'd be eager to merge this.

**Comment by pweyck** [comment]
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

**Pull request closed without merging**
