### PR TITLE
Update Migration1536233330MailTemplate.php

### PR DESCRIPTION
**Pull request by powolnymarcel**
Added missing primary key

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @powolnymarcel 
thanks for your PR :+1: 
unfortunately we could not change existing migrations, as they were already executed on systems where an update will be applied. therefore we need a new migration file which adds the primary key. would you mind, changing your PR accordingly?

**Comment by powolnymarcel** [comment]
"Jonas Elfering" from Shopware on Slack told me that he already created a fix

**Comment by mitelg** [comment]
@keulinho would you please link the fix here and close the PR? ☺️

**Comment by keulinho** [comment]
It should be fixed by this commit: https://github.com/shopware/platform/commit/6315c9e0e71a484d581b865b7e56af7e72ed14bc

closing this now

**Pull request closed without merging**
