### PR TITLE
NEXT-11875: Fix sorting of order line items

### PR DESCRIPTION
**Pull request by claudiobianco**
### 1. Why is this change necessary?
The order line items are in a different order than the cart line items.

### 2. What does this change do, exactly?
Adds sorting (position) of lineItems association.

### 3. Describe each step to reproduce the issue or behaviour.
Buy some stuff and compare the order of the line items from the cart to the order of the line items of the order.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-11875
https://issues.shopware.com/issues/NEXT-9869

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by bneumann97** [comment]
Hey @claudiobianco, thanks for your contribution 💙  Somehow your source branch is not visible or has been deleted. Could you take care of that please?

**Comment by claudiobianco** [comment]
I don't think I can recover the source branch so that the PR recognises it as such. Should I just create a new PR?

**Comment by claudiobianco** [comment]
Here is the new one #1565

**Comment by claudiobianco** [comment]
Here is the new one #1565. Sorry for the confusion.

**Pull request closed without merging**
