### PR TITLE
BUGFIX: Reactivates foreign key checks after import database.

### PR DESCRIPTION
**Pull request by mjosef89**
### 1. Why is this change necessary?
Avoid problems e.g. when swaping the default language to german.

### 2. What does this change do, exactly?
Reactivates foreign key checks after import database in CLI mode.

### 3. Describe each step to reproduce the issue or behaviour.
Run the following command:

```
php public/recovery/install/index.php \
        --no-interaction \
        --db-user=dbuser \
        --db-password=dbpassword \
        --db-name="database" \
        --db-host=localhost \
        --db-port=3306 \
        --shop-locale=de-DE \
        --shop-country=DEU \
        --shop-host=host \
        --shop-path="" \
        --shop-name='CLI Installer test' \
        --shop-currency=EUR \
        --shop-email="test@example.com" \
        --admin-username=admin \
        --admin-password=shopware \
        --admin-email=test@example.com \
        --admin-locale=de-DE \
        --admin-firstname=Test \
        --admin-lastname=Test
```
        
**Before bugfix**

In table `language` the entry "Deutsch" has the correct default id "2fbb5fe2e29a4d70aa5854ce7ce3e20b".
But because foreign key checks were disabled all `language.id` references are faulty.
For example in `country_translation` all english entries still reference the "2fbb5fe2e29a4d70aa5854ce7ce3e20b"
language_id that is now german and the german entries refer to a language_id that no longer exists.

**After bugfix**
All references to language.id are now correctly adjusted.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by bneumann97** [comment]
Hey @mjosef89, thanks for your contribution. Could you please add a changelog file?

**Comment by mjosef89** [comment]
Done.
Although it was not listed [here](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md#changelog-entries), I have "Recovery" used as a heading because my change refers to this component.

I hope this is still correct.

**Comment by bneumann97** [comment]
@mjosef89 fyi, you are only allowed to use the headers that are listed there. The correct one would be 'Core'. I'll change that for you.

**Comment by bneumann97** [comment]
Hey @mjosef89, thanks for your contribution 💙

**Pull request closed without merging**
