### PR TITLE
Enforce improved opcode by forcing global namespace references for functions and constants

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
### 1. Why is this change necessary?
Function and constant name lookup from php built-in functions and constants can be recklessly prefixed with their known namespace `\`. Beside the tests this change has a lot of LOC-wise changes on the DAL and this should be as fast as possible.

Yes, this will be a breaking change for tests that mock global functions and for other pull requests.

### 2. What does this change do, exactly?
Enforce in the php-cs-fixer style the usage of `\` for global functions and constants and enforce this rule on the complete code.

### 3. Describe each step to reproduce the issue or behaviour.
Have this sample code that uses some global functions and constants:
```php
<?php

namespace FooBar;

echo \count(\array_filter([0, 1, 2, 3], static function ($item): bool {
    return \filter_var($item, \FILTER_VALIDATE_INT);
}));
```

With manual namespace lookup and no auto lookup by adding the namespace prefix `\` the opcodes look like this:
```
line  #* I O op                      return  operands
-------------------------------------------------------
   3  0  >   NOP                             
   5  1      EXT_STMT                        
      2      INIT_FCALL                      'array_filter'
      3      EXT_FCALL_BEGIN                 
      4      SEND_VAL                        <array>
      5      DECLARE_LAMBDA_FUNCTION         '%00foobar%5C%7Bclosure%7D%2Fplatform%2Fop.php0x109172097'
   7  6      SEND_VAL                        ~0
      7      DO_FCALL                $1      
      8      EXT_FCALL_END                   
      9      COUNT                   ~2      $1
     10      ECHO                            ~2
   8 11    > RETURN                          1
```
After php internal opcode optimization
```
line  #* I O op                      return  operands
-------------------------------------------------------
   5  0  >   EXT_NOP                         
      1      RECV                    !0      
   6  2      EXT_STMT                        
      3      INIT_FCALL                      'filter_var'
      4      EXT_FCALL_BEGIN                 
      5      SEND_VAR                        !0
      6      SEND_VAL                        257
      7      DO_FCALL                $1      
      8      EXT_FCALL_END                   
      9      VERIFY_RETURN_TYPE              $1
     10    > RETURN                          $1
   7 11*     EXT_STMT                        
     12*     VERIFY_RETURN_TYPE              
     13*   > RETURN                          null
```
Without manual namespace lookup and auto lookup by missing out the namespace prefix `\` the op codes look like this:
```
line  #* I O op                      return  operands
-------------------------------------------------------
   3  0  >   NOP                             
   5  1      EXT_STMT                        
      2      INIT_NS_FCALL_BY_NAME           'FooBar%5Ccount'
      3      EXT_FCALL_BEGIN                 
      4      INIT_NS_FCALL_BY_NAME           'FooBar%5Carray_filter'
      5      EXT_FCALL_BEGIN                 
      6      SEND_VAL_EX                     <array>
      7      DECLARE_LAMBDA_FUNCTION         '%00foobar%5C%7Bclosure%7D%2Fplatform%2Fop.php0x102389093'
   7  8      SEND_VAL_EX                     ~0
      9      DO_FCALL                $1      
     10      EXT_FCALL_END                   
     11      SEND_VAR_NO_REF_EX              $1
     12      DO_FCALL                $2      
     13      EXT_FCALL_END                   
     14      ECHO                            $2
   8 15    > RETURN                          1
```
After php internal opcode optimization
```
line  #* I O op                      return  operands
-------------------------------------------------------
   5  0  >   EXT_NOP                         
      1      RECV                    !0      
   6  2      EXT_STMT                        
      3      INIT_NS_FCALL_BY_NAME           'FooBar%5Cfilter_var'
      4      EXT_FCALL_BEGIN                 
      5      SEND_VAR_EX                     !0
      6      FETCH_CONSTANT          ~1      'FooBar%5CFILTER_VALIDATE_INT'
      7      SEND_VAL_EX                     ~1
      8      DO_FCALL                $2      
      9      EXT_FCALL_END                   
     10      VERIFY_RETURN_TYPE              $2
     11    > RETURN                          $2
   7 12*     EXT_STMT                        
     13*     VERIFY_RETURN_TYPE              
     14*   > RETURN                          null
```  

Although the php internal optimization is able to reduce the unoptimized code by one operation and increases the opcode in the pre-optimized code by two, the opcode pre-optimized version does has less operations by default and was able to completely erase the closure and constant and function name lookup. The constant got replaced by its real value. This is just a thing that natively compiled languages have.

The erradicated opcode `INIT_NS_FCALL_BY_NAME` by manual pre-optimized is implemented like this

https://github.com/php/php-src/blob/00013401ff218058ff621dd681f74d228ecce9bb/ext/opcache/Optimizer/zend_optimizer.c#L802-L818

This needs several function lookups for an internal non-this-script function (which is not even checked in the first place for overriding reasons). To defend `INIT_NS_FCALL_BY_NAME` `INIT_FCALL` is sort of implemented the same but it also has a few less native operations and less cached constant values to lookup which also speeds up execution and consumes less memory (although both just a little).

https://github.com/php/php-src/blob/00013401ff218058ff621dd681f74d228ecce9bb/ext/opcache/Optimizer/zend_optimizer.c#L784-L800

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### 5. Acknowledge
Thanks to @jkrzefski to point me at a change in guzzle which made us think about internals.
Thanks to @derickr for his awesome tool to see php opcodes.

### CODE REVIEW

**Comment by uehler** [comment]
why don't you import the functions? I prefer a `use function count` on top of the file to using backslashes in the code because it keeps the code clean. In terms of performance it's the same I think.

And out of curiosity: do you have metrics of the performance impact?

**Comment by JoshuaBehrens** [comment]
Hi @uehler I can only test performance when my tests would run locally. They don't as I somehow miss GoogleClient for the Google features. I am still working on that one.

I don't like importing functions as it looks weird to me although it is technically correct. Shopware seems to think similar as their php_cs.dist file states similar rules. Having to add the backslash as well is also weird to me but if it is about performance I stretch every goal I can.

**Comment by JoshuaBehrens** [comment]
My current benchmark looks like this:
Running with php 7.4 (default max: 512MB)/mysql 5.7
I execute everytime the same steps and note down the phpunit summary.

```
psh.phar init
psh.phar init-test-databases
psh.phar unit
```

**PR-branch**

| Run | Time (h) | Memory (GB) |
|-----|----------|-------------|
| 0 | 1.49 | 3.19 |
| 1 | 1.47 | 3.11 |
| 2 | 1.5 | 3.38 |
| 6 | 1.5 | 3.55 |
| 7 | 1.42 | 2.92 |
| 8 | 1.44 | 3.21 |
| 9 | 1.51 | 2.93 |

**master-c682a1927ad4159651e110c3081a171ec6351fac**

| Run | Time (h) | Memory (GB) |
|-----|----------|-------------|
| 3 | 1.52 | 2.85 |
| 4 | 1.47 | 2.8 |
| 5 | 1.25 | 2.87 |

All in all a very inconsistent combinations of time and memory on both branches but the PR does not look good in this comparison. There is an other statistical measurement phpunit is taking: the long running tests (that were stated as long running for every run):

| Test | PR | PR | PR | master | master | master | PR | PR | PR | PR |
|------|----|----|----|-------|-------|-------|----|----|----|----|
| ImportExportTest:testProductsCsv | 201s | 206s | 205s | 195s | 189s | 195s | 192s | 189s | 194s | 192s |
| CacheClearerTest:testCleanupOldKernelDirectories | 121s | 118s | 130s | 123s | 121s | 115s | 130s | 124s | 114s | 129s |
| KernelPluginIntegrationTest:testScheduledTaskIsRegisteredOnPluginStateChange | 106s | 103s | 103s | 107s | 107s | 98s | 105s | 97s | 98s | 107s |
| KernelPluginIntegrationTest:testActivate | 105s | 103s | 103s | 106s | 103s | 97s | 106s | 98s | 98s | 107s |
| KernelPluginIntegrationTest:testKernelParameters | 105s | 102s | 102s | 106s | 105s | 98s | 107s | 96s | 97s | 107s |
| KernelPluginIntegrationTest:testDeactivate | 105s | 103s | 103s | 106s | 104s | 97s | 105s | 97s | 99s | 107s |
| ServiceDefinitionTest:testEverythingIsInstantiatable | 67s | 61s | 66s | 80s | 58s | 59s | 59s | 75s | 62s | 64s |

This is also a bit flaky but still puts the PR in a better position at some tests. So it looks like a real microoptimization when the amount of instructions is technically reduced.

As conclusion: my expectations were higher than the result.

**Comment by pweyck** [comment]
Hi @JoshuaBehrens,

we're screening old/stale PRs. Did you use an automated tool to make this change? If so, could you rebase onto master and do it again? The performance improvement should in theory be worth it.

**Comment by JoshuaBehrens** [comment]
I feel your screening already 😢 

Yes it is automated. Tight schedule though. I can get it ready for upcoming monday.

**Comment by mitelg** [comment]
14 days is tight? :astonished:

**Comment by JoshuaBehrens** [comment]
I mean like right now I am scheduled tightly so I can't publish the automated changes immediately. As external contributor two weeks can be tight because one does not always have time to continue the contribution. I get it on your side as well.

**Comment by JoshuaBehrens** [comment]
Rebase is out. The automation is just running php-cs-fixer and ecs and let them fix the code. So no additional tools needed.

**Comment by mitelg** [comment]
hey @JoshuaBehrens 
we use easy coding standard for fixing the code style now for quite some time. would be nice, if you could make the changes in the configuration files for ECS. both yml and PHP, though the yml is deprecated but still used by plugins

**Comment by JoshuaBehrens** [comment]
I will have a look how this is done in ecs. Probably similar

**Comment by mitelg** [comment]
very easy :blush: 
just add `PhpCsFixer\Fixer\FunctionNotation\NativeFunctionInvocationFixer` here https://github.com/shopware/platform/blob/master/easy-coding-standard.php#L78

**Comment by bneumann97** [comment]
Hey @JoshuaBehrens, thanks for your contribution 💙 Unfortunately this change is too big for us. Therefore, after an internal discussion, we decided to close this PR.

**Comment by JoshuaBehrens** [comment]
Either @mitelg was not part of the discussion or has been converted :O 
grafik

**Comment by mitelg** [comment]
was not part 🤷‍♂️
I'm team services and not team core 😉

(maybe I will try an internal PR 🤫😁)

**Comment by mitelg** [comment]
hey @JoshuaBehrens 

I will consider your PR as part of https://issues.shopware.com/issues/NEXT-12333 :blush: :tada:

**Comment by mitelg** [comment]
thanks for your contribution @JoshuaBehrens   👍🎉💙

**Comment by JoshuaBehrens** [comment]
Thanks @mitelg for updating it 💙

**Pull request closed without merging**
