### PR TITLE
[feature/plugin-description] Add plugin description to administration

### PR DESCRIPTION
**Pull request by lx-wnk**
### 1. Why is this change necessary?
To display a plugin description in the administration

### 2. What does this change do, exactly?
Uses the description tag inside the composer.json to display the description

### 3. Describe each step to reproduce the issue or behaviour.
Try to view the description in the administration

### 4. Please link to the relevant issues (if any).
///

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by lx-wnk** [comment]
>  I have written or adjusted the documentation according to my changes

Is there something I should adjust?

**Comment by mitelg** [comment]
hey,
thanks for your PR. :+1: 
I don't think, you need an own API route just to get the description. the data should already be available, when the plugin is fetched

**Comment by lx-wnk** [comment]
@mitelg thank you for the hint. I changed the commit according to that.

**Comment by pweyck** [comment]
Thanks for contributing :), your change was merged into master.

**Pull request closed without merging**
