### PR TITLE
Do not persist changes when cancelling inline-edit changes in sw-data-grid component

### PR DESCRIPTION
**Pull request by theErikss0n**
### 1. Why is this change necessary?

When the inline-edit is canceled [an event gets emitted](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid/index.js#L432) which is used to [save the inline-edit](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid/index.js#L425). The [event is caught](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid-inline-edit/index.js#L60) and [re-emitted](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid-inline-edit/index.js#L68) by the edit component and the grid [assigns the value](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid/sw-data-grid.html.twig#L206).

Expected behavior: Cancel action discards new value
Actual behavior: Cancel action assigns new value to grid

### 2. What does this change do, exactly?
This PR fixes this by not throwing the `inline-edit-assign` event when cancelling the inline-edit.

### 3. Describe each step to reproduce the issue or behaviour.
1. Create `sw-data-grid` with `allowInlineEdit` and `showActions` set to `true` 
2. Create at least one column with the `inlineEdit` property set to any valid value (e.g. `number`)
2. Double click on the data field and edit the value
3. Click on cancel
4. New value is assigned to the data field

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @theErikss0n 
thanks for your contribution. could you please sign the CLA?

**Comment by theErikss0n** [comment]
> hey @theErikss0n
> thanks for your contribution. could you please sign the CLA?

signed

**Comment by tobiasberge** [comment]
Hi @theErikss0n,

first of all I have to apologize. I completely missed this pull request. I have imported the pull request, we just have to check if this might cause some side-effects because of components which are based on the `sw-data-grid` like `sw-entity-listing` or `sw-one-to-many-grid`.

Best regards
Tobias

**Review by tobiasberge — APPROVED** [review]

**Comment by tobiasberge** [comment]
Hi @theErikss0n ,

thank you for your contribution. 🎉 
Your changes have been merged to `master`, see https://github.com/shopware/platform/commit/84049755a299929f05578e787e48b9298f2580e7
For some reason the merge was not automatically synced to this PR. I assume this happened because the default branch is currently `6.2`.

Best regards
Tobias

**Pull request closed without merging**
