### PR TITLE
Allow file:// urls to fetch media files from

### PR DESCRIPTION
**Pull request by teiling88**
### 1. Why is this change necessary?

to allow file:// urls to fetch images from

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
Although I really want to support this I assume this will be a problem, when file paths are not sanitized or validated, you can expose any whitelisted file on the system. But damn I sometimes need this myself.

**Comment by teiling88** [comment]
A documentation about how to import local images would make this pr useless :-D

**Comment by aragon999** [comment]
I was just about to create the same pull request, as I did not find out how to import images, without using a workaround to ftp to the same server.
As for the security issue, is that not what PHP's [open_basedir](https://www.php.net/manual/en/ini.core.php#ini.open-basedir) is for?

**Comment by JoshuaBehrens** [comment]
@aragon999 but will this be limited to paths inside the app? I assume I can import log files and have them public. Yes, there is still admin auth needed.

**Comment by aragon999** [comment]
@JoshuaBehrens if I would import files from the file system I would not like the path limited to the app directories and/or even public directories of the app. If you supply wrong data to the CSV, I am not sure if one should guard against this. Maybe one could also check some extensions or other things for the downloaded file, but these are all things which can be circumvented.
 
Maybe I do not understand the attack angle of this "security problem"?

**Comment by JoshuaBehrens** [comment]
My thought of attack that this whitelist is not solely used on a csv import but any upload to media from admin/API.

**Comment by aragon999** [comment]
I still do not get it, what is the difference if it is from a CSV than from the admin/API?

Do you mean that you could circumvent the "ACL protection" if you have rights to the media managment, in the sense that one could for example copy some logs or config files as media and then view it?

**Comment by JoshuaBehrens** [comment]
CSV is internal and admin API is externally available.

Wait ACL is already a thing?

My fear was that one can expose files that do not belong public. But the media extension whitelist and the openbase dir settings can solve my attack thoughts.

**Comment by bneumann97** [comment]
Hey @teiling88, thanks for your contribution 💙  Unfortunately this could lead to possible security issues therefor we decided to close this PR.

**Pull request closed without merging**
