### PR TITLE
fix minor translation and double space issue

### PR DESCRIPTION
**Pull request by themazim**
* fix some minor german translation issues.
* fix minor double spaces.

### 1. Why is this change necessary?
Mixed up german / english translation. 

### 2. What does this change do, exactly?
It only fixes translation which was missed.

### 3. Describe each step to reproduce the issue or behaviour.
send a german order status changed mail. 

### 4. Please link to the relevant issues (if any).
-

### 5. Checklist
seems most of the points are unnecessary. ;)
- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by pantrtxp** [comment]
Hi @themazim 

Sadly, we can not just edit migrations. Each shop that is already set up won't be able to geht these changes since only the new migrations are executed during an update.

To fix this we'd need to create a new migration which would fix the mistake and ship it with the next minor version.

Sunny regards
Pantrtxp

**Comment by themazim** [comment]
@pantrtxp  Creating a new migration would mean, that already fixed translations or changes by user would be overwritten again, which is not really good practice.

This should be more a fix for future installations, since update & install is the only time this is executed.

**Comment by mitelg** [comment]
@themazim for that reason we check in migrations if the `updated_at` column is `null`. and only update in this case

**Comment by themazim** [comment]
I created a ticket for reference: https://github.com/shopware/platform/issues/709

**Pull request closed without merging**
