### PR TITLE
NEXT-12109 | Upload media via Url can not upload media 

### PR DESCRIPTION
**Pull request by kiplingi**
### 1. Why is this change necessary?
Fixes problems caused through URL encoded image upload.

### 2. What does this change do, exactly?
Decodes URL string before it is sent to server.

### 3. Describe each step to reproduce the issue or behaviour.
See [Issue](https://issues.shopware.com/issues/NEXT-12109?products=SW-6&edition=community,starterEdition&projects=all&type=1,4&status=open,inProgress,done)

### 4. Please link to the relevant issues (if any).
[Issue](https://issues.shopware.com/issues/NEXT-12109?products=SW-6&edition=community,starterEdition&projects=all&type=1,4&status=open,inProgress,done)

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by bneumann97** [comment]
Hey @kiplingi, thanks for your contribution 💙  Could you please add a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md)

**Comment by kiplingi** [comment]
Sure

**Comment by kiplingi** [comment]
Hi @bneumann97, I added the log, but now the tests fail,I don't see how it relates to the changes of the PR. Also the ShopwareBot opened an issue, but there already is one open for this.

**Comment by bneumann97** [comment]
@kiplingi, a rebase should fix the failing tests. The ticket is created for our internal workflow.

**Comment by bneumann97** [comment]
The failing build has nothing to do with your change. We are fixing it internally 😉

**Comment by J-Rahe** [comment]
Hey @kiplingi, thanks for your contribution.

**Pull request closed without merging**
