### PR TITLE
Normalize phpstan config

### PR DESCRIPTION
**Pull request by szepeviktor**
See the 2 commits inside.

Related to #84 but phpstan's `%rootDir%` does not work when installed by Phive

### CODE REVIEW

**Comment by szepeviktor** [comment]
It turns out Phive is OKAY: https://github.com/phpstan/phpstan/issues/2286

**Comment by szepeviktor** [comment]
Tests may be very special: _Found 1265 errors_

phpstan-tests.neon

```yaml
# Start: tools/phpstan analyse -c phpstan-tests.neon
parameters:
    inferPrivatePropertyTypeFromConstructor: true
    level: 2
    paths:
        - %rootDir%/../src/Core/Migration/Test/
        - %rootDir%/../src/Core/Checkout/Test/
        - %rootDir%/../src/Core/Framework/Test/
        - %rootDir%/../src/Core/Content/Test/
        - %rootDir%/../src/Core/System/Test/
        - %rootDir%/../src/Elasticsearch/Test/
        - %rootDir%/../src/Storefront/Test/
    autoload_directories:
        - %rootDir%/../src/Core/Framework/Test/Plugin/_fixture/plugins/SwagTest/src/
        - %rootDir%/../src/Core/System/Test/SystemConfig/_fixtures/SwagExampleTest/
        - %rootDir%/../src/Core/System/Test/SystemConfig/_fixtures/SwagInvalidTest/
    autoload_files:
        - %rootDir%/../src/Core/Framework/Test/FeatureFlag/_fixture/feature_nextfix101.php
        - %rootDir%/../src/Core/Framework/Test/FeatureFlag/_fixture/feature_nextfix102.php
        # CallableClass is in
        - %rootDir%/../src/Core/Framework/Test/DataAbstractionLayer/EntityRepositoryTest.php
    ignoreErrors:
        # TODO Add reason
        - '#^(Used function|Function) Flag\\\S+ not found\.$#'
        # For BC with Symfony 4
        - '#^Method Symfony\\Contracts\\EventDispatcher\\EventDispatcherInterface::dispatch\(\) invoked with 2 parameters, 1 required\.$#'
```

...regarding the HttpKernel errors (about **one thousand**) could be resolved by upgrading symfony/* packages to 3.4.2 (3.4.1 has an error)

**Comment by szepeviktor** [comment]
@pweyck Could you please look at this?

**Comment by mitelg** [comment]
hey @szepeviktor 
thanks for your PR. I'm currently working on rebuilding our CI pipeline. I have taken some of your changes into my PR. It will be merged soon

**Pull request closed without merging**
