### PR TITLE
Support FkField as primary key in CriteriaQueryHelper

### PR DESCRIPTION
**Pull request by jkrzefski**
### 1. Why is this change necessary?
When you create an entity definition that is meant to be an extension of another entity, you could make the primary key of the base entity your own primary key and simultaneously make it a foreign key by using an `FkField`. If you try to get a list of your extension objects via the api, you would find zero results, while the sum in `meta.total` displays the correct amount.

This happens, because the api would first search for the ids and then read with these ids. Without my change, the id is handled in its hexadecimal representation when it should be handled as binary. The CriteriaQueryHelper converts the hexadecimals to binary if the field of the primary key is an instance of `IdField` (which `FkField` is not).

### 2. What does this change do, exactly?
It accepts both `IdField` and `FkField` instances to convert the hexadecimal id into binary. This procedure is also congruent to a [different location in this same file](https://github.com/jkrzefski/platform/blob/1f54a16262535a7ed5fd5be06dc031300437a8b5/src/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryHelper.php#L170) for a similar use case.

The fix I provide here is to be seen as an intermediate solution, because this does not break BC. For a long term solution I would very much prefer to use the actual serializer that comes with the primary key field itself. However, that requires to have a context at this point (which we don't have), so it breaks BC.

### 3. Describe each step to reproduce the issue or behaviour.
1. Have an entity definition with an `FkField` as your primary key.
2. Create some entries in the database for this entity.
3. Make a get-request to the rest-api to get a list of your entries.
4. See no entries, but the correct sum of your entries in the api-response.

### 4. Please link to the relevant issues (if any).
None.

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by OliverSkroblin** [comment]
Hi @jkrzefski,

thanks for your contribution. Can you please provide some tests for this change? Otherwise we can not simply merge a change inside the DAL

**Comment by jkrzefski** [comment]
@OliverSkroblin Yes, I can do that.

**Comment by jkrzefski** [comment]
I finally made a test 😅
Some (seemingly) unrelated test is failing for php 7.4 though. Can anyone tell me why?

**Comment by mitelg** [comment]
was expecting a meme :smile: slightly disappointed, so here we go:

**Comment by mitelg** [comment]
could not restart, for unknown reason :thinking: but should be ok. it will be tested with out internal CI anyway

**Comment by bneumann97** [comment]
Hey @jkrzefski, thanks for your contribution 💙 It would be great if you could add some more test cases. A single test is not enough for a change in the DAL.

**Comment by jkrzefski** [comment]
@bneumann97 I can do that. But it would be helpful if you could tell me what the tests should do. 🤔

**Comment by bneumann97** [comment]
* Fetching an entity with fk as primary
* Fetching an entity aggregation with fk as primary
* Fetching an association with fk as primary
* Fetching an association with fk as primary and add id condition in the association criteria
* Fetching an association with fk as primary and set a limit in the association criteria
	* "Fetching an association" cases with one to many
	* "Fetching an association" cases with many to many
	* "Fetching an association" cases with one to one

**Comment by bneumann97** [comment]
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

**Pull request closed without merging**
