### PR TITLE
Update 610-setup-mail-templates-and-mail-configuration.md

### PR DESCRIPTION
**Pull request by bystro**
I think we should define the `MAILER_URL` instead of  a`MAIL_URL` as SwiftMailer is used https://symfony.com/doc/current/email.html

### CODE REVIEW

**Comment by ssltg** [comment]
@bystro thank you for your contribution. The PR should point to the master instead of 6.1 and can you please sign the license/cla?

greets

**Comment by bystro** [comment]
have no idea why travis checks fail

**Comment by mitelg** [comment]
@bystro don't worry. the travis build is not reliable right now unfortunately. I'm sure, that our internal Gitlab CI will pass with your changes :wink:

**Comment by bystro** [comment]
@mitelg What do you mean saying about "license/cla" ?

**Comment by tobiasberge** [comment]
Hi @bystro,

thank you for your contribution. 🎉 
Your changes have been merged to `6.2`.

Best regards
Tobias

**Pull request closed without merging**
