### PR TITLE
Fixes #1109 Update domain info on update-records pagination

### LINKED ISSUE #1109: Admin request check?domain is not called in plugins list for pages 2 and above
**Description**  
`https://[server]/api/v1/_action/system-config/check?domain=[plugin].config` is not called for plugins on page 2 or higher with in Plugins list. This results in the plugin config not being accessible.

See this video for details.

https://[server]/admin#/sw/plugin/index/list?
[Bildschirmvideo aufnehmen 2020-07-07 um 18.02.24.zip](https://github.com/shopware/platform/files/4885897/Bildschirmvideo.aufnehmen.2020-07-07.um.18.02.24.zip)

limit=25&page=1&sortBy=upgradedAt&sortDirection=desc&naturalSorting=false

This can be fixed by loading the page with a higher limit at the moment.

### PR DESCRIPTION
**Pull request by runelaenen**
### 1. Why is this change necessary?
Domain info is not triggered for plugins on pages > page 1.

### 2. What does this change do, exactly?
Listen to the @update-records event of the listing and load the domain info of the plugins on the new page.

### 3. Describe each step to reproduce the issue or behaviour.
Explained in issue #1109 

### 4. Please link to the relevant issues (if any).
#1109 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by bneumann97** [comment]
Hey @runelaenen, thanks for your contribution 💙  Please change your target branch to major as this could lead to breaks.

**Comment by runelaenen** [comment]
Hi @bneumann97 I've changed the base branch and fixed a merge conflict.

**Comment by J-Rahe** [comment]
Hey @runelaenen, could you please add an changelog and test?

**Comment by philipreinken** [comment]
Hello, we're closing this pull request due to inactivity. If this change is still important to you, feel free to create a new pull request.

For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline.

**Pull request closed without merging**
