### PR TITLE
Cms video elements css typo

### PR DESCRIPTION
**Pull request by PheysX**
### 2. What does this change do, exactly?
Change scss variables typo from heigth to height in youtube and vimeo cms block / element.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by Haberkamp** [comment]
Hey, could you please squash your commits into one commit?

**Comment by PheysX** [comment]
Im not sure how this works @Haberkamp

**Comment by keulinho** [comment]
Hey @PheysX,

it's easiest to squash you commits with an interactive rebase aka `git rebase -i`.
This [guide](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_changing_multiple) should give you the necessary info.

Kind regards
Jonas

**Comment by PheysX** [comment]
Got it i guess, not sure if the force push was the right way 😅

**Comment by Haberkamp** [comment]
@PheysX thank you for you contribution. Your PR has been merged 🎉

**Pull request closed without merging**
