### PR TITLE
add FileSaverInterface to make it Decoratable

### PR DESCRIPTION
**Pull request by henrikvolmer**
### 1. Why is this change necessary?
To make to FileSaver Decoratable for own CDN Plugin

### 2. What does this change do, exactly?
add FileSaverInterface to make it Decoratable

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by pweyck** [comment]
Hello @henrikvolmer,

could you elaborate more why you need this change? Why isn't it sufficient to change the flysystem adapter?

**Comment by henrikvolmer** [comment]
Hello @pweyck,

sorry for my slightly delayed answer :)

I want to integrate my own CDN. That means that when e.g. an image is uploaded in the SW backend, it will be stored directly into the CDN.

BTW: For the development of plugins, I think it always makes sense to use interfaces. Otherwise the services must be extended "dirty" :)

**Comment by bcremer** [comment]
There should be no need to decorate or change `FileSaver` as you already can change the internal filesystem implementation being used with your own implementation of the `FilesystemInterface`.

`FileSaver` is a facade that contains the glue code to handle the communication with the underling filesystems that do the actual fileoperations like for example CDN uploads etc.

https://github.com/shopware/platform/blob/a25a5664110a028fadf78bbc6e9f763b9897224d/src/Core/Content/Media/File/FileSaver.php#L98-L99

**Comment by pweyck** [comment]
FYI: We've just finished refactoring our asset system: https://github.com/shopware/platform/commit/cb6dddac39a984bc5af73d5f7c085be0c6b2f181

I'm closing this, I think this has no relevance anymore. Please correct me, if I'm wrong @henrikvolmer.

**Pull request closed without merging**
