### PR TITLE
Add security prompt before plugin uninstall with possibility for save uninstall

### PR DESCRIPTION
**Pull request by felixbrucker**
### 1. Why is this change necessary?
Currently, a plugin can only be completely uninstalled via the plugin manager, which means that all plugin data is also irretrievably removed. 
There is also no security question whether you really want to uninstall the plugin.

### 2. What does this change do, exactly?
This PR adds the ability to uninstall a plugin without removing the data. This allows you to reinstall the plugin.
It also adds a security prompt.

grafik

### 3. Describe each step to reproduce the issue or behaviour.
Not applicable.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-4521

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
Did you added it also to the cli commands?

**Comment by pweyck** [comment]
Nice work! :blue_heart: I've merged it into the 6.3.0.0 branch.

**Comment by JoshuaBehrens** [comment]
AAAAAAAAAAAAAAAAAAH

**Comment by JoshuaBehrens** [comment]
This basically reverts https://github.com/shopware/platform/pull/456 :(

**Pull request closed without merging**
