### PR TITLE
Fix typo in api versioning documentation

### PR DESCRIPTION
**Pull request by hanneswernery**
### 2. What does this change do, exactly?

Fixes a typo in the api versioning documentation.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by pantrtxp** [comment]
Hi @hanneswernery,

you still need to accept our CLA. :)

**Comment by hanneswernery** [comment]
True.

I just fixed that.

**Comment by pantrtxp** [comment]
@hanneswernery Github still says "Pending — Contributor License Agreement is not signed yet."

I can not import your PRs until the CLA is accepted due to legal reasons.
Please accept it [here](https://cla-assistant.shopware.com/shopware/platform?pullRequest=646)

Sunny regards
pantrtxp

**Comment by hanneswernery** [comment]
Hmm I tried again. Maybe now?
Screenshot 2020-03-23 at 09 41 56

**Comment by pantrtxp** [comment]
Thank you for your contribution :blue_heart:

**Pull request closed without merging**
