### PR TITLE
Fix call structure of the DocumentApiService

### PR DESCRIPTION
**Pull request by Agreon**
### 1. Why is this change necessary?

When creating a document for an order the list of documents and the order information is reloaded _immediately_ while the create (or upload) request is still pending (See [document.api.service.js:33-49](https://github.com/shopware/platform/blob/7138594ed4cf472970339735eedb5aac9fb44f17/src/Administration/Resources/app/administration/src/core/service/api/document.api.service.js#L33-L49)).
Therefore if the server takes some time to create a document, the page is reloaded without the new document.

Screenshot 2021-01-06 at 09 42 27

There is also a wrong use of the `docCreated` variable that leads to an JS error in the developer console

Screenshot 2021-01-06 at 10 00 59

### 2. What does this change do, exactly?

With this PR the create/upload response of the document creation is correctly awaited and therefore the document list is reloaded _after_ the document was created.
It also fixes the JS error.

### 3. Describe each step to reproduce the issue or behaviour.

Simulate a slow document creation (e.g. adding `sleep(5);` to the `DocumentGeneratorController`). Create a document for any order. The page will be reloaded and the new document is missing in the document list.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Review by philipreinken — CHANGES_REQUESTED** [review]
Hi @Agreon , thank you for creating this pull request 🙂 Please add a regression test for your changes, so we can be sure this issue won't come up again.

**Comment by Agreon** [comment]
Hi @philipgatzka!
It seems like there is already a test checking that behaviour. Unfortunately you seem to have adjusted it to work with the faulty code (https://github.com/shopware/platform/commit/1c11b21aeec00064ba2264558b11f570d466150c#). In lines 104-110 you manually reload the page so that you can be sure that the document request is done. Unfortunately that is exactly what a user has to do if the request takes too long... I would suggest removing these lines because now we can be sure it is loaded at that time. 
Could you otherwise give me an example on how to simulate a delay in a request?

**Review by philipreinken — APPROVED** [review]
Hi @Agreon , sorry for the late reply. Makes sense, by removing the code executing the workaround, the correct behaviour is tested implicitly already, so that approach works for me 👍🏼 Regarding your question, Jest provides [fake timers](https://jestjs.io/docs/en/timer-mocks) which can be used for testing timing-dependent code.

**Comment by J-Rahe** [comment]
Hey @Agreon, there were some changes leading to merge conflicts for your PR, could you please rebase?

**Comment by Agreon** [comment]
@J-Rahe i already resolved the conflicts

**Comment by J-Rahe** [comment]
@Agreon, did you maybe forgot to push them? i just checked your branch out again and your last changes are from the 6.01 while the already merged changes are from 20.01. Would be nice if you could check that : )

**Comment by bneumann97** [comment]
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

**Pull request closed without merging**
