### PR TITLE
fix path rename of "@Storefront/storefront" also for "ide-twig.json" to allow PhpStorm to be working on template resolving

### PR DESCRIPTION
**Pull request by Haehnchen**
Move `ide-twig.json` to support 6.1 also in PhpStorm see related issues here: https://github.com/Haehnchen/idea-php-shopware-plugin/issues/113

### CODE REVIEW

**Comment by jdambacher** [comment]
Thanks for your fast response!

**Comment by pantrtxp** [comment]
Hi @Haehnchen,

it is not planned to relase another 6.1 release due to the 6.2 release in the near future.
If this issue exists on the master branch as wenn you could set this PR to the current master (which will be our 6.2 release)

Sunny Regards
Pantrtxp

**Comment by Haehnchen** [comment]
@pantrtxp done, targeting master now

**Comment by PaddyS** [comment]
Hey @Haehnchen,

thank you for your contribution! 💙 
We've just merged it! :-)

**Pull request closed without merging**
