### PR TITLE
Bug/fix cache key generation

### PR DESCRIPTION
**Pull request by FalkoHilbert**
add handling for multiple primary keys in CachedEntityReader.php

### 1. Why is this change necessary?

to handle muliple primary-keys in examlpe for many-to-many-relations in CachedEntityReader

### 2. What does this change do, exactly?

generate concatinated keys for primary-keys and use it as index for caching

### 3. Describe each step to reproduce the issue or behaviour.

create an entityDefinition with multiple primaryKeys and request them via Api

### 4. Please link to the relevant issues (if any).

https://issues.shopware.com/issues/NEXT-7497
#610 

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
I requested a similar change https://github.com/shopware/platform/pull/1107 although I do not provide a test (shame on me) you seem to have a different approach why it bothered you in the first place.

**Comment by FalkoHilbert** [comment]
> I requested a similar change #1107 although I do not provide a test (shame on me) you seem to have a different approach why it bothered you in the first place.

I had the change done for quite a while and also had a PR: #986, but then I was unavailable for a while, which is why I then rejected it.

**Comment by JoshuaBehrens** [comment]
So the work has been done three times by now? :D unlucky

**Comment by FalkoHilbert** [comment]
@pweyck and @bneumann97 why is my PR not processed?

**Comment by FalkoHilbert** [comment]
@shyim why is the cla task blocking in this PR?

**Comment by mitelg** [comment]
@FalkoHilbert please be patient. 
we work through the PRs one by another :blush: 
please do not ping the people on every PR you made

**Comment by FalkoHilbert** [comment]
> @FalkoHilbert please be patient.
> we work through the PRs one by another 😊
> please do not ping the people on every PR you made

@mitelg I didn't want to be pushy, but unfortunately all my PR's have been ignored for weeks.
If PR's are not reviewed, it somehow takes away the joy of contributing.

**Comment by mitelg** [comment]
this of course nothing personally :blush: there are 111 open PRs and only a few colleagues who are working on them. Unfortunately it currently takes some time to get after them

**Comment by J-Rahe** [comment]
Hey @FalkoHilbert, sorry that it took so long. Hopefully once we have the mountain of old PRs down we will be able to respond a bit faster : ).
 I just tested your PR (manually and by executing the test you provided) and it seems this has already been fixed.
Would be great if you could confirm that i didn`t miss anything, and if you want it would be nice if you could still provide the test case you already wrote to make sure the bug wont come back (would still need an changelog).

**Comment by J-Rahe** [comment]
Hey @FalkoHilbert, any info on this? Also you should change the branch back to master.

**Comment by shyim** [comment]
@FalkoHilbert 

With the renaming of our branches. This PR got closed. Can you create a new one pointing to trunk?

**Pull request closed without merging**
