### PR TITLE
Add LineItem cover if it's available

### PR DESCRIPTION
**Pull request by AlexBachmann**
Add the cover image of the order line item entity to the cart line item if it is available

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by pantrtxp** [comment]
Hi @AlexBachmann 

You still need to sign our CLA :) 

Sunny regards
Pantrtxp

**Comment by AlexBachmann** [comment]
Just did.

**Comment by pantrtxp** [comment]
@AlexBachmann could you please add tests?

Sunny regards
Pantrtxp

**Comment by pantrtxp** [comment]
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.

For more information about our contribution guidelines, see https://developers.shopware.com/contributing/contribution-guideline/.

**Pull request closed without merging**
