### PR TITLE
NEXT-8546

### PR DESCRIPTION
**Pull request by jkrzefski**
### 1. Why is this change necessary?
The `SystemConfigService` would not return the values that were written to it. This inconsistency meant that values of e.g. `0` were not possible.

### 2. What does this change do, exactly?
Remove a faulty early return in the resolution of config arrays.

### 3. Describe each step to reproduce the issue or behaviour.
1. Set a config key's value to `0`.
2. Get said config keys value. It is now `null`.

### 4. Please link to the relevant issues (if any).
https://github.com/shopware/platform/issues/861

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Review by OliverSkroblin — APPROVED** [review]

**Comment by leichteckig** [comment]
QA approved :heavy_check_mark:

**Comment by mitelg** [comment]
@jkrzefski please squash the commits

**Comment by jkrzefski** [comment]
@mitelg Squashed

**Comment by shyim** [comment]
Thanks for your Contribution! 💙

**Pull request merged**
