### PR TITLE
Review author added

### PR DESCRIPTION
**Pull request by Isengo1989**
### 1. Why is this change necessary?
Google is throwing an error on missing author in reviews (since they are with less credebility)

Auswahl_315

### 2. What does this change do, exactly?
Add the author with the correct item

Auswahl_316

### 3. Describe each step to reproduce the issue or behaviour.
You can test it here -> https://search.google.com/structured-data/testing-tool?hl=de#

### 4. Please link to the relevant issues (if any).
-

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by pantrtxp** [comment]
Hi @Isengo1989, you still need to accept the "Contributor License Agreement" before we can go on and merge this PR

**Comment by Isengo1989** [comment]
> Hi @Isengo1989, you still need to accept the "Contributor License Agreement" before we can go on and merge this PR



> Hi @Isengo1989, you still need to accept the "Contributor License Agreement" before we can go on and merge this PR

Done

**Comment by Isengo1989** [comment]
@pantrtxp is there still missing smth?

**Comment by pantrtxp** [comment]
Hi @Isengo1989,

we need to discuss this internally, since this is a change in the appearance this has to be discussed with our deign team.

Sunny regards
Pantrtxp

**Comment by Weltraumakustik** [comment]
Hej @Isengo1989,
thank you for your contribution!

We've looked into this closely as it's not just a visual change. 

For us it's important to safeguard customers privacy, that's why we need to make sure customers can send their review anonymously. They are then published as a “Verified Buyer” since we know they bought the product they are reviewing.

Given these facts our team will look into this and make sure everything works as intended, from your side no further work is required. 

We will implement an option for customers to send reviews anonymously, make sure names are being displayed correctly and implement the „Verified Buyer“ option. 

We’ve opened an issue for our teams, use this issue to track the state of your pull request: https://issues.shopware.com/issues/NEXT-7751

Thank you for your contribution and commitment to the shopware community!

Dennis

**Pull request closed without merging**
