### PR TITLE
NEXT-7553 - Fix link to the data protection regulations in contact form

### PR DESCRIPTION
**Pull request by Devcommerce**

### CODE REVIEW

**Comment by Phil23** [comment]
Is this a PR from the BoostDay? Then it is pointing to the wrong branch. Please also fill out the description template.

**Comment by Devcommerce** [comment]
Sorry, my mistake :-)

**Comment by Devcommerce** [comment]
1. Why is this change necessary?
Fixes #932 .

2. What does this change do, exactly?
Fix link to the data protection regulations in contact form

3. Describe each step to reproduce the issue or behaviour.

4. Please link to the relevant issues (if any).

**Comment by shyim** [comment]
Your PR contains only other changes. Can you fix that?

**Pull request closed without merging**
