### PR TITLE
Added missing import to documentation

### PR DESCRIPTION
**Pull request by TaiKamilla**
There was a missing step on the documentation

### CODE REVIEW

**Comment by mitelg** [comment]
hey @TaiKamilla 
thanks for your contribution :+1: could you please squash your commits?

**Comment by pantrtxp** [comment]
@TaiKamilla please set this PR to the master branch since we won't release another 6.1 version.

**Comment by pantrtxp** [comment]
Hi @TaiKamilla,

your PR is now pending since 12 days. 
Please update your PR or we will close it due to inactivity.

Sunny regards
Pantrtxp

**Comment by pantrtxp** [comment]
@TaiKamilla could you still need to squash your commits please

**Comment by TaiKamilla** [comment]
> @TaiKamilla could you still need to squash your commits please

@pantrtxp 
Done!

**Comment by pantrtxp** [comment]
Thank you for your contribution :blue_heart: :tada:

**Comment by TaiKamilla** [comment]
@pantrtxp 
Why does the PR shows as closed and not as merged if it was "Accepted"?
It feels like it was rejected :sweat_smile:

**Comment by mitelg** [comment]
@TaiKamilla that is because we import your PR into our internal Gitlab, where we store our source code. The code is synced to GitHub.
Most of the times we need a rebase of your commit after the import, because it is quite old, and then the commit hash changes of course. That's why we add a short snippet to the commit messages like `closes #638`. This commands GitHub to close the PR with a reference to the commit.
Also the label "Accepted" tells you the truth :wink:

**Pull request closed without merging**
